version: '3.8'
services:
    server:
        build:
            context: .
            target: server
        ports:
            - "8000:8000"
        command: >
            /bin/sh -c "
                cargo build --release &&
                cargo run --release
            "
    client: 
        build:
            context: .
            target: client
        depends_on:
            - server
        command: >
            /bin/sh -c "
                wait-for-it server:8000 --timeout=1000 &&
                cargo test --test e2e_test
            "